### ISSUE TITLE
<SNR>53_NewBufferManager error when open vim

### ISSUE THREAD

**Issue by Angluca** [jeetsukumaran/vim-buffersaurus#8]
Error detected while processing function <SNR>53_NewBufferManager:
line  154:
E128: Function name must start with a capital or "s:": l:buffer_manager:detect_filetype(fname)
line  162:
E121: Undefined variable: a:fname
E15: Invalid expression: 'doautocmd filetypedetect BufRead ' . a:fname
Press ENTER or type command to continue

**Comment by jeetsukumaran** [comment]
Please check your version and make sure that you are using the latest one from the repository (fbec3bf).

**Comment by Angluca** [comment]
Oh sorry, I use vim-scripte git before.
